version: '3.3'

services:
  php:
    container_name: $name_php
    build:
      context: php
      args:
        TIMEZONE: ${TIMEZONE}
    volumes:
      - ressources_$name:/var/www/symfony
      - ./logs/symfony:/var/wwww/symfony/var/log
    networks:
      - $name_net
  mysql:
    container_name: $name_mysql
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql/datas:/var/lib/mysql
    ports:
      - ${MYSQL_PORT}:3309
    networks:
      - $name_net
  nginx:
    container_name: $name_nginx
    depends_on:
      - php
      - mysql
    build:
      context: nginx
      args:
        MAX_EXECUTION_TIME: ${MAX_EXECUTION_TIME}
        SERVER_NAME: ${SERVER_NAME}
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - DOMAIN_NAME=${VIRTUAL_HOST}
    volumes:
      - ressources_$name:/var/www/symfony
      - ./logs/nginx:/var/log/nginx
    networks:
      - $name_net
    expose:
      - 80
    ports:
      - "${NGINX_PORT}:80"
volumes:
  ressources_$name:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/${SYMFONY_APP_PATH}
      o: bind
networks:
  $name_net:
